version: 2

defaults: &defaults
  # each command runs in separate shell with this working_directory
  working_directory: ~/repo
  docker: 
    - image: trion/ng-cli-e2e:7.2.1

jobs:
  buildweb:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:42:65:e6:01:1e:76:77:9a:60:35:bf:56:0a:8f:d3"
      - run:
          name: Avoid bitbucket.org authenticity warning for non-interactive mode
          command: |
            # editing ~/.ssh/config did not work, so using this method:
            mkdir ~/.ssh/ && ssh -oStrictHostKeyChecking=no -T git@bitbucket.org

      - checkout

      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export WEB_COMPONENT_FOLDER="services/web"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV

      - restore_cache:
          keys:
          # NOTE: once start installing multiple services in this app, we will have
          #   to update the checksum to include the other services as well
          - v1-dependencies-{{ checksum "services/web/package.json" }}
          # fallback to using the latest cache it no exact match is found
          - v1-dependencies-

      - run: cd $WEB_COMPONENT_FOLDER && npm install

      - run: 
          name: Installing pm2 used for webservice-ci task
          command: cd $WEB_COMPONENT_FOLDER && npm install pm2 -g

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "services/web/package.json" }}

      # - run: ng build --prod --no-progress

      - run: cd $WEB_COMPONENT_FOLDER && npm run test:prod-ci

      - run:
          name: Startup data webservice for e2e tests
          command: cd $WEB_COMPONENT_FOLDER && pm2 start npm -- run webservice-ci

      - run: cd $WEB_COMPONENT_FOLDER && npm run e2e

workflows:
  version: 2
  buildweb_and_test:
    jobs:
      - buildweb


