version: 2

defaults: &defaults
  # each command runs in separate shell with this working_directory
  working_directory: ~/repo
  docker: 
    - image: trion/ng-cli-e2e:7.2.1

jobs:
  buildweb:
    <<: *defaults
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:42:65:e6:01:1e:76:77:9a:60:35:bf:56:0a:8f:d3"
      - run:
          name: Avoid bitbucket.org authenticity warning for non-interactive mode
          command: |
            # editing ~/.ssh/config did not work, so using this method:
            mkdir ~/.ssh/ && ssh -oStrictHostKeyChecking=no -T git@bitbucket.org

      - checkout

      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export WEB_COMPONENT_FOLDER="services/web"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV

      - restore_cache:
          name: Restoring cache (node dependencies)
          keys:
          # v1 => package manager is node 6 (update cache version if npm version changes)
          - v1-npm-dep-{{ checksum "services/web/package.json" }}
          # fallback to using the latest cache it no exact match is found
          - v1-npm-dep-

      # NOTE: we wish to run "npm install" even if node_modules exist, so that
      #   security audit checks are always done (and errors correctly breaking our pipeline)
      - run: 
          name: Installing node modules
          command: cd $WEB_COMPONENT_FOLDER && npm install

      - save_cache:
          name: Saving cache (node dependencies)
          paths:
            - node_modules
          key: v1-npm-dep-{{ checksum "services/web/package.json" }}

      - restore_cache:
          name: Restoring cache (global node packages)
          keys:
          - v2-npm-global-pm2-3.3.1

      - run: 
          name: Installing pm2 used for webservice-ci task
          command:  |
            cd $WEB_COMPONENT_FOLDER
            npm install pm2@3.3.1 -g

      - save_cache:
          name: Saving cache (global node packages)
          paths:
            - /usr/local/lib/node_modules/pm2/bin
            - /usr/local/bin/pm2
            - /usr/local/bin/pm2-dev
            - /usr/local/bin/pm2-runtime
            - /usr/local/bin/pm2-docker
          key: v2-npm-global-pm2-3.3.1

      # - run: ng build --prod --no-progress

      - run: cd $WEB_COMPONENT_FOLDER && npm run test:prod-ci

      - run:
          name: Startup data webservice for e2e tests
          command: cd $WEB_COMPONENT_FOLDER && pm2 start npm -- run webservice-ci

      - run: cd $WEB_COMPONENT_FOLDER && npm run e2e

workflows:
  version: 2
  buildweb_and_test:
    jobs:
      - buildweb


